Activity:
    type: object
    config:
        fields:
            id:
                type: "ID!"
            name:
                type: "String!"
            email:
                type: "String"
            timezone:
                type: "String"
            gender:
                type: "String"
            dateOfBirth:
                type: "String"
            activity:
                type: "Activity"
            hobbies:
                type: "String"
            emergencyPhone:
                type: "String"
            emergencyName:
                type: "String"
            dateTimeAdded:
                type: "String"
            friendPhone:
                type: "String"
            operatorPhone:
                type: "String"
            healthData:
                type: "[healthData]"
                